### ISSUE TITLE
CRC error

### ISSUE THREAD

**Issue by 5shekel** [TeenyRiot/TeenyRiot#1]
seems the sha256 is not correct for 0.22

**Comment by 5shekel** [comment]
issue with my system, under **sudo arduino** it updates correctly.

**Comment by badgeek** [comment]
@5shekel thanks! what bootloader you are using?

**Comment by 5shekel** [comment]
its still not cool. even in under sudo im getting 
`
Warning: platform.txt from core 'TeenyRiot' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.
Warning: platform.txt from core 'TeenyRiot' contains deprecated recipe.preproc.macros="{compiler.path}{compiler.cpp.cmd}" {compiler.cpp.flags} {preproc.macros.flags} -mmcu={build.mcu} -DF_CPU={build.f_cpu} -DARDUINO={runtime.ide.version} -DARDUINO_{build.board} -DARDUINO_ARCH_{build.arch} {compiler.cpp.extra_flags} {build.extra_flags} {includes} "{source_file}", automatically converted to recipe.preproc.macros="{compiler.path}{compiler.cpp.cmd}" {compiler.cpp.flags} {preproc.macros.flags} -mmcu={build.mcu} -DF_CPU={build.f_cpu} -DARDUINO={runtime.ide.version} -DARDUINO_{build.board} -DARDUINO_ARCH_{build.arch} {compiler.cpp.extra_flags} {build.extra_flags} {includes} "{source_file}" -o "{preprocessed_file_path}". Consider upgrading this core.

`

**Comment by badgeek** [comment]
what arduino version you have?

**Comment by 5shekel** [comment]
at least the CRC error is gone...

**Comment by 5shekel** [comment]
1.6.7

**Comment by badgeek** [comment]
it works just fine for me on 1.6.8, could you delete any files related to teenyriot in /root/.arduino15/packages/ and  /root/.arduino15/staging/ and reinstall from board manager?

**Comment by 5shekel** [comment]
i did that, it's really wired.  i suspect its my system doing the weirdness.

**Comment by badgeek** [comment]
maybe that it also arduino ide issue.. it behave weirdly too sometimes... i got this warning on old version of the board, recent version doesnt have this warning
